name: brieflow_configuration
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3.11
  - snakemake=8
  - pip
  - ipykernel
  - pandas
  - numpy
  - pyyaml
  - scikit-image
  - joblib
  - cellpose # TODO: pin version if reproducbility is important (version may change segmentations)
  - pytables
  - microfilm
  - seaborn
  - mahotas
  - pip:
      - -e .
